server:
  port: 8083

spring:
  application:
    name: graph-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password

cors:
  allowed-origins: "http://localhost:3000"
